### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by JHsGame** [InfiniBrains/gdcm-unity#1]
Before going into the main content, I can't speak English. Therefore, please understand that I use a translator.

There is no Unity package, how can I import it into Unity?

And I don't see any examples of how to use it, so could you tell me an example where I can read the Dicom files?

I'd really appreciate it if you could tell me because it's my first time in this field.

**Comment by tolstenko** [comment]
Hi @JHsGame I made this glue a long time ago. I bet this wont work with any newer unity version. So I strongly recommend using this instead. https://github.com/fo-dicom
Have a nice day.
